import type { CanvasPresetId, StylePreset } from "./types";

export const CANVAS_PRESETS: Record<
  Exclude<CanvasPresetId, "custom">,
  { width: number; height: number; label: string }
> = {
  "16:9": { width: 1920, height: 1080, label: "16:9 · 1920×1080" },
  "4:3": { width: 1600, height: 1200, label: "4:3 · 1600×1200" },
  "1:1": { width: 1080, height: 1080, label: "1:1 · 1080×1080" },
  "9:16": { width: 1080, height: 1920, label: "9:16 · 1080×1920" },
  "3:2": { width: 1800, height: 1200, label: "3:2 · 1800×1200" },
  og: { width: 1200, height: 630, label: "OG · 1200×630" },
};

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: "dusk",
    name: "Dusk",
    harmony: "analogous",
    gradientType: "linear",
    angle: 148,
    lockHue: true,
    baseHue: 18,
    satMin: 42,
    satMax: 78,
    lightMin: 28,
    lightMax: 78,
    grain: { intensity: 38, opacity: 22, size: 1.4, colored: false },
    texture: { id: "tracing-paper", opacity: 28, blend: "multiply" },
    swatches: ["#f4a261", "#e76f51", "#c44536"],
  },
  {
    id: "aurora",
    name: "Aurora",
    harmony: "analogous",
    gradientType: "radial",
    angle: 210,
    lockHue: true,
    baseHue: 168,
    satMin: 38,
    satMax: 72,
    lightMin: 22,
    lightMax: 72,
    grain: { intensity: 32, opacity: 18, size: 1.2, colored: true },
    texture: { id: "film-grain", opacity: 24, blend: "soft-light" },
    swatches: ["#2a9d8f", "#57c5b6", "#159895"],
  },
  {
    id: "noir",
    name: "Noir",
    harmony: "monochromatic",
    gradientType: "linear",
    angle: 125,
    lockHue: true,
    baseHue: 250,
    satMin: 8,
    satMax: 28,
    lightMin: 8,
    lightMax: 46,
    grain: { intensity: 48, opacity: 30, size: 1.1, colored: false },
    texture: { id: "film-grain", opacity: 36, blend: "overlay" },
    swatches: ["#1b1b22", "#3d3a4a", "#6e6a7a"],
  },
  {
    id: "citrus",
    name: "Citrus",
    harmony: "complementary",
    gradientType: "linear",
    angle: 38,
    lockHue: true,
    baseHue: 36,
    satMin: 48,
    satMax: 82,
    lightMin: 36,
    lightMax: 76,
    grain: { intensity: 24, opacity: 14, size: 1.6, colored: false },
    texture: { id: "none", opacity: 0, blend: "multiply" },
    swatches: ["#f4d35e", "#ee964b", "#0d9488"],
  },
  {
    id: "orchid",
    name: "Orchid",
    harmony: "triadic",
    gradientType: "conic",
    angle: 200,
    lockHue: true,
    baseHue: 292,
    satMin: 34,
    satMax: 68,
    lightMin: 30,
    lightMax: 74,
    grain: { intensity: 28, opacity: 16, size: 1.3, colored: true },
    texture: { id: "vellum", opacity: 22, blend: "multiply" },
    swatches: ["#c084fc", "#67e8f9", "#f9a8d4"],
  },
  {
    id: "fog",
    name: "Fog",
    harmony: "monochromatic",
    gradientType: "radial",
    angle: 180,
    lockHue: true,
    baseHue: 210,
    satMin: 6,
    satMax: 22,
    lightMin: 58,
    lightMax: 92,
    grain: { intensity: 20, opacity: 18, size: 2.1, colored: false },
    texture: { id: "tracing-paper", opacity: 40, blend: "multiply" },
    swatches: ["#e7ecef", "#c5d1d8", "#9aa8b1"],
  },
  {
    id: "ember",
    name: "Ember",
    harmony: "split-complementary",
    gradientType: "linear",
    angle: 162,
    lockHue: true,
    baseHue: 12,
    satMin: 40,
    satMax: 76,
    lightMin: 18,
    lightMax: 62,
    grain: { intensity: 42, opacity: 24, size: 1.25, colored: false },
    texture: { id: "canvas-weave", opacity: 26, blend: "overlay" },
    swatches: ["#9b2226", "#bb3e03", "#0a9396"],
  },
  {
    id: "tide",
    name: "Tide",
    harmony: "analogous",
    gradientType: "linear",
    angle: 204,
    lockHue: true,
    baseHue: 212,
    satMin: 36,
    satMax: 70,
    lightMin: 24,
    lightMax: 78,
    grain: { intensity: 26, opacity: 16, size: 1.5, colored: false },
    texture: { id: "vellum", opacity: 18, blend: "multiply" },
    swatches: ["#023e8a", "#0077b6", "#90e0ef"],
  },
];
