import type { CanvasPresetId, StylePreset } from "./types";

export const CANVAS_PRESETS: Record<
  Exclude<CanvasPresetId, "custom">,
  { width: number; height: number; label: string }
> = {
  "16:9": { width: 1920, height: 1080, label: "16:9 · 1920×1080" },
  "4:3": { width: 1600, height: 1200, label: "4:3 · 1600×1200" },
  "1:1": { width: 1080, height: 1080, label: "1:1 · 1080×1080" },
  "9:16": { width: 1080, height: 1920, label: "9:16 · 1080×1920" },
  "3:2": { width: 1800, height: 1200, label: "3:2 · 1800×1200" },
  og: { width: 1200, height: 630, label: "OG · 1200×630" },
};

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: "mist",
    name: "Mist",
    harmony: "monochromatic",
    gradientType: "linear",
    angle: 162,
    lockHue: true,
    baseHue: 208,
    satMin: 6,
    satMax: 16,
    lightMin: 62,
    lightMax: 90,
    grain: { enabled: true, opacity: 16 },
    swatches: ["#d8e2e8", "#c5d0d6", "#9aa8b0"],
  },
  {
    id: "sand",
    name: "Sand",
    harmony: "analogous",
    gradientType: "linear",
    angle: 148,
    lockHue: true,
    baseHue: 34,
    satMin: 12,
    satMax: 26,
    lightMin: 62,
    lightMax: 88,
    grain: { enabled: true, opacity: 14 },
    swatches: ["#efe4d4", "#e2d0b8", "#cbb89a"],
  },
  {
    id: "sage",
    name: "Sage",
    harmony: "analogous",
    gradientType: "radial",
    angle: 200,
    lockHue: true,
    baseHue: 132,
    satMin: 8,
    satMax: 20,
    lightMin: 46,
    lightMax: 80,
    grain: { enabled: true, opacity: 18 },
    swatches: ["#d5ddd4", "#b7c4b5", "#8a9a88"],
  },
  {
    id: "clay",
    name: "Clay",
    harmony: "analogous",
    gradientType: "linear",
    angle: 156,
    lockHue: true,
    baseHue: 16,
    satMin: 14,
    satMax: 28,
    lightMin: 52,
    lightMax: 84,
    grain: { enabled: true, opacity: 16 },
    swatches: ["#ead8d0", "#d4b8ae", "#b89286"],
  },
  {
    id: "haze",
    name: "Haze",
    harmony: "monochromatic",
    gradientType: "radial",
    angle: 180,
    lockHue: true,
    baseHue: 268,
    satMin: 6,
    satMax: 16,
    lightMin: 58,
    lightMax: 88,
    grain: { enabled: true, opacity: 15 },
    swatches: ["#e6e2ea", "#cfc8d6", "#a79eaf"],
  },
  {
    id: "drift",
    name: "Drift",
    harmony: "analogous",
    gradientType: "linear",
    angle: 204,
    lockHue: true,
    baseHue: 198,
    satMin: 10,
    satMax: 22,
    lightMin: 44,
    lightMax: 82,
    grain: { enabled: true, opacity: 17 },
    swatches: ["#d5e3e6", "#b4c8cd", "#7f969c"],
  },
  {
    id: "linen",
    name: "Linen",
    harmony: "monochromatic",
    gradientType: "linear",
    angle: 128,
    lockHue: true,
    baseHue: 42,
    satMin: 5,
    satMax: 14,
    lightMin: 72,
    lightMax: 94,
    grain: { enabled: true, opacity: 12 },
    swatches: ["#f4f0e8", "#e6e0d4", "#cfc6b6"],
  },
  {
    id: "smoke",
    name: "Smoke",
    harmony: "monochromatic",
    gradientType: "linear",
    angle: 138,
    lockHue: true,
    baseHue: 28,
    satMin: 4,
    satMax: 12,
    lightMin: 18,
    lightMax: 54,
    grain: { enabled: true, opacity: 22 },
    swatches: ["#2c2a28", "#4a4642", "#7a746c"],
  },
];
